services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Mount the entire project directory
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - WATCHDOG_TIMEOUT=5
    command: >
      streamlit run app/main.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.runOnSave=true
      --server.fileWatcherType=poll
      --server.headless=true